[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/preview-4827-armbx"
  to = "/preview-4827-armbx/"
  status = 301
