[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/preview-4827-armbx"
  to = "/preview-4827-armbx/index.html"
  status = 200

[[redirects]]
  from = "/preview-4827-armbx/"
  to = "/preview-4827-armbx/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/under-construction.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/under-construction.html"
  status = 200
